### ISSUE TITLE
Dark theme not available on Linux

### ISSUE THREAD

**Issue by gronastech** [deepkit/deepkit#1]
![image](https://user-images.githubusercontent.com/48826970/65747075-2e583a00-e109-11e9-87cd-38eaca230dd4.png)

**Comment by marcj** [comment]
This is fixed in v0.0.5. Thanks for reporting! You can change the theme now in application settings.

**Comment by marcj** [comment]
Oh as I see, this is not totally fixed yet.

**Comment by marcj** [comment]
This is now fixed with the release of the official version. See https://deepkit.ai/ for more information.
