### ISSUE TITLE
Docker Mounts

### ISSUE THREAD

**Issue by anthonytec2** [deepkit/deepkit#20]
I have tried the most recent version of DeepKit and cant get Docker mounts to work. I go to the node where I want to use them, change the settings in mounts to /home/anthony/data:/data, this works locally but using DeepKit this mount does not appear.

I get the error:
```
run failed Error: (HTTP code 400) unexpected - invalid environment variable:  
(HTTP code 400) unexpected - invalid environment variable:  
```

**Comment by anthonytec2** [comment]
Further, if I then define an env variable, I get the new error:
```
run failed Error: (HTTP code 500) server error - invalid volume specification: ':undefined' 
(HTTP code 500) server error - invalid volume specification: ':undefined'
```

**Comment by marcj** [comment]
Which linux and Docker version do you use on the cluster node? Also please post your configuration file, so I can try to replicate.

**Comment by anthonytec2** [comment]
Sorry, after rebooting the node the error does not persist. I can see the volume now.

**Comment by marcj** [comment]
Mh, that's weird. The 500 comes from the Docker daemon. I wonder what the issue was. Please ping me when you experience the same issue again so we can hunt it down.
