### ISSUE TITLE
please windows version ?

### ISSUE THREAD

**Issue by iperov** [deepkit/deepkit#5]
I want it very much.

**Comment by marcj** [comment]
Not yet planned. We will write here once we started implementation.

**Comment by asbe** [comment]
I'm able to run it under WSL by manually editing the shell script for the deepkit cli. Seems to work, but have not tested it properly yet.

**Comment by marcj** [comment]
@asbe cool, what did you change?

**Comment by asbe** [comment]
@marcj hardcoded paths in `deepkit` shellscript, mainly - installer in gui borks for no apparent reason. Deepkit app needs to be run sudo with `--no-sandbox` option. (Also - you need to run a xserver and export proper `DISPLAY`, of course. ).

Is there a reason why you use a bundled node? 

I'll fire up one of the examples from the deepkit-python-sdk and report back when things start to crash.

**Comment by marcj** [comment]
Windows version is now available as experimental, but don't expect too much. See https://deepkit.ai. I haven't found yet a way to make CLI available in windows terminal. We just lack windows developer experience. 🤷‍♂️

**Comment by cyfwry** [comment]
您好，您发给我的邮件已收到！
